package view;

import com.sun.deploy.util.ArrayUtil;
import model.Facility;
import util.EarthUtil;
import util.WWJUtil;

import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
import java.util.ArrayList;
import java.util.Collections;

/**
 * @author mohammad
 */
public class FacilityDialog extends javax.swing.JDialog {

    /**
     * Creates new form FacilityDialog
     */
    public FacilityDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        facilityTree = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setType(java.awt.Window.Type.POPUP);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("JTree");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("colors");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("blue");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("violet");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("red");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("yellow");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("sports");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("basketball");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("soccer");
        javax.swing.tree.DefaultMutableTreeNode treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("football");
        javax.swing.tree.DefaultMutableTreeNode treeNode6 = new javax.swing.tree.DefaultMutableTreeNode("hockey");
        treeNode5.add(treeNode6);
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("food");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("hot dogs");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("pizza");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("ravioli");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("bananas");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        facilityTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        facilityTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                facilityTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(facilityTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

/*****************************************************************************************/
/*************************************  METHODS  *****************************************/
    /*****************************************************************************************/
    private static DefaultListModel<Facility> model = new DefaultListModel<>();

    private void facilityTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) ((JTree) evt.getSource()).
                getLastSelectedPathComponent();
        if (selectedNode.getChildCount() == 0) {
            Facility facility = (Facility) selectedNode.getUserObject();
            WWJUtil.getUserFacilities().add(facility);
            model.addElement(facility);
            Root.facilityList.setModel(model);
        }
    }

    public static DefaultListModel<Facility> getModel() {
        return model;
    }

    /************************************************************************************************/
/************************************************************************************************/
    /************************************************************************************************/

    // Variables declaration - do not modify
    public static javax.swing.JTree facilityTree;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration
}
