package view;


import javax.swing.*;
import java.awt.*;
import java.util.Calendar;

/**
 * @author Mohammad
 */
@SuppressWarnings({"FieldCanBeLocal", "UnusedParameters"})
public class ResultDialog extends javax.swing.JDialog {

    /**
     * Creates new form ResultDialog
     */
    ResultDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(71, 95, 133));
        setFocusCycleRoot(false);
        setFocusable(false);
        setFocusableWindowState(false);
        setLocation(new java.awt.Point(1100, 150));
        setPreferredSize(new java.awt.Dimension(410, 630));
        setResizable(false);

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/exitt.png"))); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator2)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap(342, Short.MAX_VALUE)
                                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(456, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>


    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int confirmed = JOptionPane.showConfirmDialog(null,
                "آیا تمایل دارید محاسبات ذخیره شود ؟", "خروج",
                JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            this.setVisible(false);
        } else {
            Root.resultDialog = new ResultDialog(null, false);
            this.setVisible(false);
        }
    }

    private void settingButtonActionPerformed(java.awt.event.ActionEvent evt) {

        SettingDialog settingDialog = new SettingDialog(null, false);

        Root.resultDialog.setVisible(false);

        settingDialog.setVisible(true);

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        ResultDialog dialog = new ResultDialog(null, true);

        JPanel panel = new JPanel(new GridLayout(100, 1));

        for (int i = 0; i < 100; i++) {

            JPanel panel1 = new JPanel(new GridLayout(1, 1));

            ResultPanel resultPanel = new ResultPanel();
            Color color = new Color(71, 95, 133);
            resultPanel.setColor(color);
            resultPanel.sat.setText("RSDK-ONE");
            resultPanel.pic.setIcon(new javax.swing.ImageIcon(dialog.getClass().getResource("/resource/" + "RSDK-ONE" + ".png")));

            Calendar cal = Calendar.getInstance();
            cal.add(Calendar.MINUTE, 2);
            resultPanel.setStartDate(cal.getTime());
            resultPanel.time.setText("1395/02/01  13:28:40 - 13:31:20 ");

            resultPanel.run();

            panel1.add(resultPanel);
            panel.add(panel1);

        }

        JScrollPane scrollPane = new JScrollPane(panel);

        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setBounds(5, 30, 400, 540);

        dialog.add(scrollPane);

        dialog.setVisible(true);
    }

    // Variables declaration - do not modify
    private javax.swing.JButton closeButton;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration

}